### ISSUE TITLE
Request with OData $select query option fails

### ISSUE THREAD

**Issue by nickciaravella** [Microsoft/Intune-Data-Warehouse#5]
When sending a request with the $select OData query option, the request will fail with HTTP status code 500 and error message "An internal server error has occurred". 

**Example request:** 
https://fef.msua06.manage.microsoft.com/ReportingService/DataWarehouseFEService/dates?$select=dateKey&api-version=beta

**Example response:**
{
    "Message":"An internal server error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 00000000-0000-0000-0000-000000000000 - Url: https://fef.msua06.manage.microsoft.com/ReportingService/DataWarehouseFEService/%24select%3DdateKey?api-version=beta - CustomApiErrorPhrase: "
}

**Comment by adamlandmsft** [comment]
Thanks Nick, we do not currently support $select (see https://docs.microsoft.com/en-us/intune/reports-api-url) but unfortunately it is returning a misleading HTTP 500 instead of 400. We are currently working on adding support for $select.

**Comment by nickciaravella** [comment]
The work to support $select has been completed. Closing this issue.
